Use 'Strict*' type explicitly instead of aliasing them to Python builtin types. MyPy flags the type aliases as errors, e.g.:
    error: Variable "models.cvr.str" is not valid as a type

"Explicit is better than implicit" anyway.